version: '2'
networks:
  default:
    external:
      name: proxy_default
services:
  sec:
    build:
      context: .
      dockerfile: Dockerfile-prod
    volumes:
      - .:/app/server
      - ./database:/db
    environment:
      - WARDEN_TOKEN=some_secure_password
